#!/bin/bash 

make SteadyState

if [ "$?" = "0" ]; then
    # ./$exe   -pc_type jacobi -ksp_monitor_short #-ksp_plot_eigenvalues_explicitly -draw_pause -1 #-ksp_monitor_singular_value -ksp_monitor_true_residual
    mpirun -n 6 ./SteadyState  -ksp_monitor_short -ksp_type lgmres -ksp_gmres_restart 3000  -ksp_converged_reason -pc_type jacobi 
    #-malloc_log
#    mpirun -n 6 ./SteadyState -ksp_monitor_short -ksp_type gmres -ksp_gmres_restart 3000  -ksp_converged_reason -pc_type gamg -pc_gamg_sym_graph true -ksp_rtol 1.e-11  -mg_levels_pc_type jacobi
    #        mpirun -n 6 ./SteadyState -ksp_monitor_short -ksp_type tfqmr -pc_type jacobi -ksp_converged_reason 
# mpirun -n 6 ./SteadyState -ksp_monitor_short -ksp_converged_reason -ksp_type bicg  -pc_type jacobi -log_summary
    

    #-ksp_gmsdfres_modifiedgramschmidt
    #-log_summary
    # -malloc_log
    #-ksp_plot_eigenvalues_explicitly -draw_pause -1 
    #> screen_log.OUT
#        mpirun -n 6 ./$exe -ksp_type bicg -pc_type jacobi  -ksp_monitor_short #-draw_pause -1 #-mat_view draw 
else
    rm $exe
    exit 1
fi

